// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjy9xnsefCKUOVdhRGGRgHLaFP2a4GyE',
    appId: '1:211388663455:web:819408c6e628fd48bec4aa',
    messagingSenderId: '211388663455',
    projectId: 'pandara-health',
    authDomain: 'pandara-health.firebaseapp.com',
    storageBucket: 'pandara-health.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySRN6H66IpWqx-f74qkUuRr-fQkdgV2c',
    appId: '1:211388663455:android:a844facc706466c9bec4aa',
    messagingSenderId: '211388663455',
    projectId: 'pandara-health',
    storageBucket: 'pandara-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsy9QW6hX4_hQ140kOwHD1dvRMO3EgGUA',
    appId: '1:211388663455:ios:1656d473e7727b6cbec4aa',
    messagingSenderId: '211388663455',
    projectId: 'pandara-health',
    storageBucket: 'pandara-health.firebasestorage.app',
    iosBundleId: 'com.example.pandaraHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsy9QW6hX4_hQ140kOwHD1dvRMO3EgGUA',
    appId: '1:211388663455:ios:1656d473e7727b6cbec4aa',
    messagingSenderId: '211388663455',
    projectId: 'pandara-health',
    storageBucket: 'pandara-health.firebasestorage.app',
    iosBundleId: 'com.example.pandaraHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFjy9xnsefCKUOVdhRGGRgHLaFP2a4GyE',
    appId: '1:211388663455:web:0c7e381adae66a60bec4aa',
    messagingSenderId: '211388663455',
    projectId: 'pandara-health',
    authDomain: 'pandara-health.firebaseapp.com',
    storageBucket: 'pandara-health.firebasestorage.app',
  );
}
